spring:
  application:
    name: geojero-server
  profiles:
    active: local

server:
  port: 8080

cors:
  allowed-origins:
    - http://localhost:5173
    - https://www.geojero.com
    - https://geojero-client.vercel.app
    - https://geojero-client-*.vercel.app

logging:
  pattern:
    correlation: "[%X{traceId:-................}] "

management:
  endpoints:
    web:
      exposure:
        include: health